=== Nindzzya/indesignjs/Teil_III/14_XML/kochbuch-grammatik.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--	Eine einfache DTD -->

<!-- 	Ein einziges Wurzelelment umschließt alle Kindelementem. 
	Es muss mindestens ein rezept-Element angelegt werden -->
<!ELEMENT 	kochbuch (rezept+) >

<!--	Rezepte bestehen aus einem Container mit dem Titel, den Zutaten und einer Beschreibung -->
<!ELEMENT 	rezept (titel, u-zwischen?, zutaten, u-zwischen?, beschreibung, bild-container?) >

<!--	Mit dem Attribut id wird eine eindeutige Identifizierung pro Rezept vorgenommen,
	mit dem Attribut art kann das Rezept einer bestimmten Rezeptklasse zugewiesen werden -->
<!ATTLIST 	rezept
		id ID #IMPLIED
		art  (vorspeise|hauptgericht|dessert) #REQUIRED>

<!ELEMENT 	titel (#PCDATA )>

<!-- Container-Element für zutaten-->
<!ELEMENT   zutaten (zutat+) >
<!-- Container-Element für einzelen Zutat-->
<!ELEMENT 	zutat (menge, name) >
<!ELEMENT 	menge (#PCDATA )>
<!ELEMENT 	name (#PCDATA )>


<!ELEMENT bild-container (bild,legende?)>
<!ELEMENT legende (#PCDATA )>

<!ELEMENT bild EMPTY >
<!ATTLIST bild 
            href CDATA #REQUIRED>

<!ELEMENT 	beschreibung (schritt+) >
<!--	Die einzelnen Rezeptschritte können Textdaten (PCDATA) und Hervorhebungen  
	in beliebiger Kombination enthalten-->
<!ELEMENT 	schritt (#PCDATA | fett | kursiv)*>

<!ELEMENT 	u-zwischen (#PCDATA )>

<!--Inline-Elemente -->
<!ELEMENT 	fett (#PCDATA )>
<!ELEMENT 	kursiv (#PCDATA )>

=== Nindzzya/indesignjs/Teil_III/14_XML/14_Rezepte.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE kochbuch SYSTEM "kochbuch-grammatik.dtd">
<kochbuch>
	<rezept id="i1" art="hauptgericht">
		<titel>Pizzateig</titel>
		<zutaten>
			<zutat>
				<menge>400 g</menge>
				<name>Weizenmehl &lt; Type 550</name>
			</zutat>
			<zutat>
				<menge>200 ml</menge>
				<name>Wasser</name>
			</zutat>
			<zutat>
				<menge>1 Pck.</menge>
				<name>frische Hefe</name>
			</zutat>
			<zutat>
				<menge>1 TL</menge>
				<name>Meersalz</name>
			</zutat>
		</zutaten>
		<beschreibung>
			<schritt>Das <kursiv>Mehl</kursiv> auf die Arbeitsfläche geben, in der Mitte eine Mulde für die Hefe drücken.</schritt>
			<schritt>Die <kursiv>Hefe</kursiv> in etwas <kursiv>Wasser</kursiv> auflösen, in die Mulde geben und vermengen.</schritt>
			<schritt>Nach und nach das Wasser zugeben, das <kursiv>Salz</kursiv> einarbeiten und zu einem geschmeidigen Teig verkneten.</schritt>
			<schritt>An einem warmen Ort für 1 Stunde gehen lassen.</schritt>
			<schritt>Den Teig belegen und bei mindestens <fett>250 °C</fett> ca. <fett>15 Minuten</fett> backen.</schritt>
		</beschreibung>
		<bild-container>
			<bild href="file://bilder/pizzateig.jpg"/>
		</bild-container>
	</rezept>
	<rezept id="i2" art="hauptgericht">
		<titel>Tomatensugo</titel>
		<zutaten>
			<zutat>
				<menge>1 Zehe</menge>
				<name>Knoblauch</name>
			</zutat>
			<zutat>
				<menge>1 Knolle</menge>
				<name>Zwiebel</name>
			</zutat>
			<zutat>
				<menge>1 Dose</menge>
				<name>Tomaten</name>
			</zutat>
			<zutat>
				<menge>Etwas</menge>
				<name>Rosmarin, Oregano, frisches Basilikum</name>
			</zutat>
			<zutat>
				<menge>Prise</menge>
				<name>Salz, Pfeffer</name>
			</zutat>
		</zutaten>
		<beschreibung>
			<schritt><kursiv>Zwiebeln</kursiv>, <kursiv>Knoblauch</kursiv> und <kursiv>Kräuter</kursiv> klein würfeln und in <kursiv>Olivenöl</kursiv> anschwitzen.</schritt>
			<schritt><kursiv>Tomaten</kursiv> dazugeben und etwas einkochen lassen.</schritt>
			<schritt>Nach Belieben <kursiv>Basilikum</kursiv>, <kursiv>Oregano</kursiv> und <kursiv>Rosmarin</kursiv> zugeben.</schritt>
			<schritt>Mit <kursiv>Salz</kursiv> und <kursiv>Pfeffer</kursiv> nach Geschmack abschmecken.</schritt>
			<schritt>Sugo mindestens <fett>15 Minuten</fett> einkochen lassen.</schritt>
		</beschreibung>
		<bild-container>
			<bild href="file://bilder/tomatensugo.jpg"/>
		</bild-container>
	</rezept>
	<rezept id="i3" art="dessert">
		<titel>Fatimas Versuchung</titel>
		<zutaten>
			<zutat>
				<menge>Einen</menge>
				<name>Granatapfel</name>
			</zutat>
			<zutat>
				<menge>500 g</menge>
				<name>türkischen Joghurt</name>
			</zutat>
			<zutat>
				<menge>200 ml</menge>
				<name>Sahne</name>
			</zutat>
			<zutat>
				<menge>1 Pck.</menge>
				<name>Vanillezucker</name>
			</zutat>
			<zutat>
				<menge>250 g</menge>
				<name>getrocknete Aprikosen</name>
			</zutat>	
		</zutaten>
		<beschreibung>
			<schritt><kursiv>Joghurt</kursiv> abtropfen und mit pürierten <kursiv>Aprikosen</kursiv> vermischen.</schritt>
			<schritt><kursiv>Granatapfel</kursiv> auslösen, und in den Joghurt einrührern.</schritt>
			<schritt><kursiv>Sahne</kursiv> schlagen mit <kursiv>Vanillezucker</kursiv> steif schlagen.</schritt>
			<schritt>Sahne unter die Joghurtcreme heben.</schritt>
			<schritt>Die Creme kalt stellen.</schritt>
		</beschreibung>
	</rezept>

</kochbuch>
